import ToasterContext from '@/context/ToasterContext'
import '../style/globals.css'
import type { Metadata } from 'next'
import UserContext from '@/context/UserState'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ToasterContext />
        <UserContext>
          {children}
        </UserContext>
      </body>
    </html>
  )
}
