import ToasterContext from '@/context/ToasterContext'
import '../style/globals.css'
import type { Metadata } from 'next'
import GroupModal from '@/components/modal/GroupModal'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <GroupModal/>
        <ToasterContext />
          {children}
      </body>
    </html>
  )
}
